name: MarkBind Deploy

on: [push]

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Standard deployment to GitHub Pages
      # files are at the root of the repository
      # version specified is v3.1.0
      - name: Build & Deploy to GitHub Pages
        uses: tlylt/markbind-deploy@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          baseUrl: '/mb-test'
          version: '3.1.0'