name: MarkBind Deploy

on: [push]

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy to GitHub Pages
        uses: tlylt/markbind-deploy-gh-pages@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          baseUrl: 'mb-test'
          version: 'master'