name: MarkBind Deploy

on:
  push:
    branches:
      - main

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy to GitHub Pages
        uses: tlylt/markbind-deploy@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
