name: Build Fork PR

# read-only
# no access to secrets
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: Unpublish from Surge
    uses: tlylt/markbind-reusable-workflows/.github/workflows/unpublish-preview.yml@main
    with:
      version: "3.1.1"
      baseUrl: ""